# Generated by Django 2.2.5 on 2019-09-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0003_auto_20190927_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Heroi',
        ),
    ]
