# Generated by Django 2.2.5 on 2019-09-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0006_auto_20190927_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='nivel_habilidade',
        ),
    ]
